### ISSUE TITLE
'else if' keyword implementation to lexer.c

### ISSUE THREAD

**Issue by berkenvr** [tile-lang/tile-frontend-c#3]
All implementations of 'else if' keyword done but i need help about how to implement it in lexer.c. There are 'if' and 'else' keywords, so how should i code the 'else if'? For example:
```c
{ "if", TOKEN_IF }, 
{ "else if", TOKEN_ELSEIF }, // TODO: 'else if' or 'elseif' which one?
{ "else", TOKEN_ELSE },
```

in this example the lexer try to notice 'else if' in input, but it will return the 'else' token and then 'if' token. So 'else if ' is not going to be returned. Should i write 'elseif' instead of it (in this solution syntax will be change). Is there a solution to do that without changed syntax of tile language?

**Comment by yasinxdxd** [comment]
"else if" is not a token, if something has a white space it means that there are two tokens?!
So that means that it is the job of parser. If we try to solve this on lexer, it will be so hard to implement a system that allow user to write code like this:
```c
if (condition) {
    /*...*/
} 
else             if (condition2) {
    /*...*/
} else    if (condition3) {
    /*...*/
}
```

**Comment by berkenvr** [comment]
I got it what you mean. So im deleting the 'else if' token from lexer.
