### ISSUE TITLE
True and false implementation to lexer.c

### ISSUE THREAD

**Issue by berkenvr** [tile-lang/tile-frontend-c#4]
True and false keywords implemented all files but it needs little bit improvement about that topic:
So user can write 'true', 'True', 'TRUE' etc. (same for 'false'), the current version of lexer only notice the 'true' and 'false'.
It should recognize other possibilities.

**Comment by yasinxdxd** [comment]
it shouldn't recognize, there is no high level language that recognize other possibilities out there. The reason tasm recognize some keywords without respecting wheter it is upper case or lower case is because other assemblers usually do it like that. But There is no such a high level lang.
